# Generated by Django 3.1.1 on 2021-11-17 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20211117_1209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
