# Generated by Django 3.1.1 on 2021-11-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
