# Generated by Django 3.1.1 on 2021-11-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0010_publisher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
